### PR TITLE
#Issue657 has been fixed. Added Movie Recommender website in the webapp section.

### PR DESCRIPTION
**Pull request by ParnaRoyChowdhury777**
I have added a Movie Recommender Website made in ReactJS and TailwindCSS with proper fetching of Movie APIs under the webapp section of projects assigned to me under #Issue657 under GSSOC' 24. Here is a screenshot of my project 

movie1

### CODE REVIEW

**Comment by ParnaRoyChowdhury777** [comment]
Sir, please check this once. I committed at night yesterday. But since Another pr was merged today morning, it is showing branch conflicts to me. Can u please check it once, sir?

**Comment by ParnaRoyChowdhury777** [comment]
@SyedImtiyaz-1 Please check once.

**Comment by SyedImtiyaz-1** [comment]
Hello @ParnaRoyChowdhury777 ,
All set,
But it's a request to add the project folder inside the projects section.

Just add the project files and push in the same branch then I'll merge it.

**Comment by ParnaRoyChowdhury777** [comment]
I have sent another PR correcting all the issues. Please check it once, Sir.

**Pull request closed without merging**
