### PR TITLE
Solved #673- Music Visualizer

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
Solved #673 
Music_Visualizer
Music_Visualizer1

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review now

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge this PR

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Resolved the changes 
Kindly label and merge

**Comment by SyedImtiyaz-1** [comment]
All good, just add the project in project folder.

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Done the required changes

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly merge sir

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly review and approve

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1 
Kindly merge this PR

**Comment by Aditi22Bansal** [comment]
@SyedImtiyaz-1
Kindly merge this PR

**Pull request closed without merging**
