### PR TITLE
Added Youtube video downloader

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
Added Youtube video downloader #437 

image

### CODE REVIEW

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Give atleast level3 label

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Have a look.

**Comment by SyedImtiyaz-1** [comment]
resolve conflicts

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Done

**Pull request merged**
