### PR TITLE
Added animated counter

### LINKED ISSUE #333: [ui-upgrade]: Inclusion of number counting effect
**Describe the bug**
The counting number effect doesn't work correctly eventhough it was raised as an issue.

**To Reproduce**
Steps to reproduce the behavior 
1.Go to the homepage.
2.Scroll to the statistics section.
3.Observe the counters.
4.Add the optimal code for counting number effect.

**Expected behavior**
Counters should animate smoothly from 0 to the target number specified in the data-target attribute

**Screenshots**
Screenshot_20240528_131931_Chrome

**Additional context**
This issue was previously assigned under hacktoberfest but issue is not solved..
Thereby kindly assign to me under gssoc'24 to correct it and kindly add level labels.

- [X] I have checked the existing issues
- [X] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [X] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [X] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

### PR DESCRIPTION
**Pull request by swetha5157**
Closes #333
### **Description:**
* Included the animated counter upon scrolling which will add a feather to this wonderful Precious IT Services project.

### **Test:**
I have tested the code and it works well

### **Screenshots/Video:**

https://github.com/SyedImtiyaz-1/GetTechProjects/assets/123291594/8e1b4202-a2a0-4f4b-a042-fa5df1115441

I have followed the Code of Conduct and Contributing Guidelines
Kindly add level labels for the issue #333

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Good Work @swetha5157

**Comment by SyedImtiyaz-1** [comment]
Reverts https://github.com/SyedImtiyaz-1/GetTechProjects/pull/364

I'm unmerging your PR which is also called reverting because the project is not visible you have to add the proejct in drive first of all then add the link, name and img in the backend>public>proejcts.json 👍🏻

**Comment by swetha5157** [comment]
But I have enhanced the feature not added any new projects..

**Comment by SyedImtiyaz-1** [comment]
> But I have enhanced the feature not added any new projects.. Or should I add the image and link even if it is feature enhancement. Kindly clarify.

Sorry My Fault.

**Comment by swetha5157** [comment]
Thankyou @SyedImtiyaz-1 for merging my contribution

**Pull request merged**
