### PR TITLE
Score Trcker added

### PR DESCRIPTION
**Pull request by Yashgabani845**
i have added score tracker project 
this had two section crikcte and football
each of section trace  this things 

fixes : #405 
- live score
- sechdule
- upcoming series
- player states
- head to head 
- player names

 i have added entry in json and images in image folder 
 
 # ScreenShot of entry
 
Screenshot (233)

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 
kindly review and mege this PR

**Comment by SyedImtiyaz-1** [comment]
@Yashgabani845  Make the drive link public.

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1  done kindly check it

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1  i have made it publlic

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 Please give me a review so I can resolve the conflicts

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 i have resolved all the merge conflicts aslo
can you please review,merge it

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 
please check my PR i have made all the required changes
it is pending from last few days
it would be great if you check it

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 i have chnaged and solved merge confloct please check it

**Comment by SyedImtiyaz-1** [comment]
Hello @Yashgabani845 ,
It's a request to add the folder(files) in projects folder.

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 
done sir
please check it

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 added and solved merge conflicts as well 
please proceed to merge and look at files i am adding before giving label

**Comment by SyedImtiyaz-1** [comment]
Not Resolved.

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 Done 
sir i  am resolving but beaucse of many PRs getting merged now so it is creating new conflict it is done now

**Pull request closed without merging**
