### PR TITLE
Fixed the bug in description at about page

### PR DESCRIPTION
**Pull request by ananyag309**
Issue: #694 
I have corrected the description 
@SyedImtiyaz-1 please add gssoc and level label, and my name under assignes.
also, thank you for assigning it.
bug fix

### CODE REVIEW

**Comment by ananyag309** [comment]
@SyedImtiyaz-1 sir please have a look. I have done the task. Please add gssoc and level label to it.

**Comment by ananyag309** [comment]
@SyedImtiyaz-1 sir please check and add gssoc and level label.

**Comment by ananyag309** [comment]
@SyedImtiyaz-1 sorry to disturb you sir, but when will my pull req be reviewed it's been a long time. Please have a check and add gssoc and level label. Thank you

**Comment by SyedImtiyaz-1** [comment]
Kindly resolve the conflicts.

**Comment by ananyag309** [comment]
@SyedImtiyaz-1 sir i have resloved the conflict. please check and add gssoc and level label

**Pull request closed without merging**
