### PR TITLE
[Feature] : E-commerce web applicatiom Added

### LINKED ISSUE #859: [Feature] : Adding `E-commerce`  web applicatiom
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- If i want to implement New project `E-commerce` web application .
- please assign me.

### Use Case

- 

### Benefits

- 

### Screenshot 
- Mobile section
Screenshot from 2024-06-28 06-53-42
- product page
Screenshot from 2024-06-28 06-54-26
- cart page
Screenshot from 2024-06-28 06-54-43

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @SyedImtiyaz-1 ,

closes #859 

- I will add the `E-commerce` web application

[Feature] : E-commerce web applicatiom Added

### Deploy site

- [Click Here](https://shopping-application-iota.vercel.app/) :rocket: ....

### Screen Shot

**Home Section**

Screenshot from 2024-07-01 20-13-48

**Mobile Section**
Screenshot from 2024-07-01 20-14-00

**Laptop Section**

Screenshot from 2024-07-01 20-17-07

**View Product Details Section**
Screenshot from 2024-07-01 20-17-20

**Cart Section**
Screenshot from 2024-07-01 20-14-14

**Login Page**
Screenshot from 2024-07-01 20-14-21

- please merge it...

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@SyedImtiyaz-1 please merge it...

**Comment by sivaprasath2004** [comment]
@SyedImtiyaz-1  please merge it...

**Comment by SyedImtiyaz-1** [comment]
@sivaprasath2004 Kindly add details in the .json folder as well as proper img of the project.

**Comment by sivaprasath2004** [comment]
@SyedImtiyaz-1 please add the `level` label, because I'm `gssoc` contributor..

**Comment by sivaprasath2004** [comment]
@SyedImtiyaz-1 please add the `level` label, because I'm `gssoc` contributor..

**Pull request merged**
