### PR TITLE
Extension hub added

### LINKED ISSUE #542: [New Project] Extension Hub Project
**Describe the bug**
it has many google chrome extension that i ahve made my self and contributed to open source
20+ chrome extension are present in this Extrension hub icluding these

1. Score tracker
2. Vpn connecter
3. Age calculator
4. to do list
5. reminder
6. chess game
7. instra reels downloader
8. youtube video downloader
 and many more....

**Screenshots**
Screenshot (197)
Screenshot (91)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

### PR DESCRIPTION
**Pull request by Yashgabani845**
it is combination of 25+  chrome extension that i have made myself and tested 
fixes #542 

i am addding this project 
list of extension in this hub 

1. 2048 game
2. age calculator
3. bitcoin price tracker
4. bmi calculator
5. chess
6. currency coverter
7. football live score
8. cricket live score
9. memory game
10. youtube video downloader
11. leetcode potd geenrator
12. languages translator
13. markdown previwer
14. network speed tester
15. world clock
16. gold price tracker
17. html css helper
18. stocks price tracker 

and few more...

i have added images and json file entry

Screenshot (302)

*ignore first commit it is already merged checkout file changes

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1  please review this PR
feel free to give feedbook 
if all well give required labels so that no conflict occure in future
thank you

**Comment by SyedImtiyaz-1** [comment]
check the drive link once.

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 
i have replaced the link previously it was drive link , i replace it with sharing link
and it is public

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 please look over it

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 
if you want i am ready to put files in projects folder

**Comment by SyedImtiyaz-1** [comment]
Hello @Yashgabani845 
Yes put the files in the projects folder.

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1
done sir as i said in desc. 
it is huge hub soo files number is too large
and also that's why i ill request for level 3

**Pull request merged**
