### PR TITLE
Added url shortener

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
Added URL Shortner #435 

image

### CODE REVIEW

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Give atleast level 2 or level3 label

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Have a look.

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Check this one too.

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Have a look to this PR too.

**Comment by priyanshukumar397** [comment]
kindly check @SyedImtiyaz-1

**Comment by thevijayshankersharma** [comment]
@SyedImtiyaz-1 Have a look to this PR too.

**Pull request merged**
