### PR TITLE
Add: Project Apple store clone

### PR DESCRIPTION
**Pull request by imohitpatel**
Add images and public pages

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Hello,
Add files in projects..json too.

**Comment by imohitpatel** [comment]
@SyedImtiyaz-1 Ok

**Comment by imohitpatel** [comment]
@SyedImtiyaz-1 please review and merge this PR And another
 `Add: Apple Store to.json`

**Review by imohitpatel — COMMENTED** [review]
Remove img

**Comment by SyedImtiyaz-1** [comment]
add it in json using public drive link.

**Comment by imohitpatel** [comment]
@SyedImtiyaz-1 please merged this PR that project public drive link and other adding to. Json already done and that #540 already merged

Please merged this for programmer  who want to get source code 
Close #487

**Pull request merged**
