### PR TITLE
coding platform added

### PR DESCRIPTION
**Pull request by Yashgabani845**
i have added codeacedemy coding platform 

Fixes : #451 
which is made using this tech stack
1. html,css,js
2. postgres
3. node-express

### screenshot of entry
Screenshot (239)

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1  kindly check my PR and review it

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 please add gssoc label

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1 if there will be no gssoc label then my contribution will not be counted kinfly please assign in sir

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 if there will be no gssoc label then my contribution will not be counted kinfly please assign in sir

No worries

**Pull request merged**
