### PR TITLE
chore: project addition by Nisarga - Real Estate App #406

### PR DESCRIPTION
**Pull request by nisargaa20**
This project covers various aspects of web development, including advanced authentication, real-world CRUD operations, user-friendly features, advanced search functionality.

Technologies Used:
🔑 Advanced Authentication: Implement JWT, Firebase, and Google OAuth for secure and seamless user access.

🏡 Real-world CRUD Operations: Create, read, update, and delete property listings using MongoDB.

💡 User-friendly Features: Enhance the user experience with image uploads, property listing management, and more.

🚀 Advanced Search Functionality: Implement cutting-edge search features to help users find what they're looking for.

Projects - Google Chrome 31-05-2024 13_29_42
Projects - Google Chrome 31-05-2024 13_29_45
Projects - Google Chrome 31-05-2024 13_29_52

This is an MERN stack projects kindly consider this project for LEVEL 3 .
Thank you for merging.

### CODE REVIEW

**Comment by nisargaa20** [comment]
@SyedImtiyaz-1 Kindly review it

**Comment by nisargaa20** [comment]
@SyedImtiyaz-1 Its been 5 days kindly revert back

**Comment by SyedImtiyaz-1** [comment]
Just resolve the conflict will merge it.

**Comment by nisargaa20** [comment]
@SyedImtiyaz-1 done. Is this project only level 1 ? Its an MERN stack project

**Comment by SyedImtiyaz-1** [comment]
@nisargaa20 Just add the folder and will give you more level as per the code.

**Comment by nisargaa20** [comment]
@SyedImtiyaz-1 
    "courseId": "Estate Square App",
      "name": "Estate Square App",
      "image": "img/estate.png",
      "downloadLink": "https://drive.google.com/file/d/1v2sXztsbys7voH4LC44kXRpfFf7od8ZG/view?usp=drivesdk",
      "techstack": "MERN Stack",
      "slide-img-1": "img/Real.png",
      "slide-img-2": "img/Real-estate_3.png"

    }

Kindly check out the google drive where code is the displayed

**Comment by SyedImtiyaz-1** [comment]
Yes it's fine.
But you have to add the project files in the project folder also. 

Add the project files in the project folder + update json. This is how you can contribute.

**Comment by nisargaa20** [comment]
@SyedImtiyaz-1 Done i have added the folder

**Pull request merged**
